CREATE DATABASE db_ecommerce
USE db_ecommerce

CREATE TABLE Usuarios(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	Cpf VARCHAR(50) NOT NULL,
	Nome VARCHAR(50) NOT NULL,
	Email VARCHAR(100) NOT NULL,
	Senha VARCHAR(100) NOT NULL,
	Endereco VARCHAR(100)NOT NULL,
	MeioPagamento VARCHAR (50) NOT NULL
)

CREATE TABLE Carrinho(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	Quantidade INT NOT NULL,
	Preco FLOAT NOT NULL,
	Frete FLOAT NOT NULL,
	Cupom FLOAT NOT NULL,
	FK_Usuario INT NOT NULL,
	FK_Produto INT NOT NULL
	FOREIGN KEY (FK_Usuario) REFERENCES Usuarios (Id),
	FOREIGN KEY (FK_Produto) REFERENCES Produtos (Id)
)

CREATE DROP TABLE Produtos(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	NomeProduto VARCHAR(50) NOT NULL,
	Categoria VARCHAR (100) NOT NULL,
	Descricao VARCHAR(150) NOT NULL,
	Preco FLOAT NULL,
	FK_Carrinho INT NOT NULL,
	FOREIGN KEY (FK_Carrinho) REFERENCES Carrinho (Id)
	
)

CREATE TABLE Pagamento(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	MetodoPagamento VARCHAR(50),
	Parcelas INT,
	FK_Usuario INT NOT NULL,
	FK_Carrinho INT NOT NULL,
	FOREIGN KEY (FK_Usuario) REFERENCES Usuarios (Id),
	FOREIGN KEY (FK_Carrinho) REFERENCES Carrinho (Id)
)


