CREATE DATABASE db_socialmedia
USE db_socialmedia

CREATE TABLE Usuarios (
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	Nome VARCHAR (100) NOT NULL,
	Email VARCHAR (100) NOT NULL,
	Senha VARCHAR (50) NOT NULL

)

CREATE TABLE Grupos (
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	Grupo VARCHAR (80) NOT NULL,
	Descricao VARCHAR (100) NOT NULL,
	UrlImagem VARCHAR (200) NOT NULL,
	FK_Usuario INT NOT NULL

)

CREATE TABLE Postagens ()

CREATE TABLE Tema ()